BitSolutions/Controllers/ContatoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Net.Mail;

namespace BitSolutions.Controllers
{
    public class ContatoController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        private Boolean ValidaPreenchimento(string txtNome, string txtEmail, string txtMensagem)
        {
            if (txtNome.Equals(String.Empty))
            {
                return false;
            }
            if (txtEmail.Equals(String.Empty))
            {
                return false;
            }
            if (txtMensagem.Equals(String.Empty))
            {
                return false;
            }
            if (txtNome.Equals(String.Empty))
            {
                return false;
            }
            if (!txtEmail.Contains("@") || !txtEmail.Contains("."))
            {
                return false;
            }
            return true;
        }

        [HttpPost]
        public ActionResult EnviaEmail()
        {
            String txtNome = Request["txtNome"];
            String txtEmail = Request["txtEmail"];
            String txtMensagem = Request["txtMensagem"];

            if (ValidaPreenchimento(txtNome, txtEmail, txtMensagem))
            {
                //Define os dados do e-mail
                string nomeRemetente = txtNome;
                string emailRemetente = "marcel.ogando@esolucoesdigitais.com";

                string emailDestinatario = "contato@melhoroferta.online";
                string emailComCopia = "marcel.ogando@esolucoesdigitais.com";
                string senha = "Twhccdc33f";

                string assuntoMensagem = "Uma nova mensagem de " + txtNome;
                string conteudoMensagem = txtMensagem.Replace(Environment.NewLine, "<br/>") + "<br/><br/> E-mail do remetente: " + txtEmail;

                //Host da porta SMTP
                string SMTP = "smtp.esolucoesdigitais.com";

                //Cria objeto com dados do e-mail.
                MailMessage objEmail = new MailMessage();

                //Define o Campo From e ReplyTo do e-mail.
                objEmail.From = new System.Net.Mail.MailAddress(nomeRemetente + "<" + emailRemetente + ">");

                //Define os destinatários do e-mail.
                objEmail.To.Add(emailDestinatario);

                //Enviar cópia para.
                objEmail.CC.Add(emailComCopia);

                //Define a prioridade do e-mail.
                objEmail.Priority = System.Net.Mail.MailPriority.Normal;

                //Define o formato do e-mail HTML (caso não queira HTML alocar valor false)
                objEmail.IsBodyHtml = true;

                //Define título do e-mail.
                objEmail.Subject = assuntoMensagem;

                //Define o corpo do e-mail.
                objEmail.Body = conteudoMensagem;


                //Para evitar problemas de caracteres "estranhos", configuramos o charset para "ISO-8859-1"
                objEmail.SubjectEncoding = System.Text.Encoding.GetEncoding("ISO-8859-1");
                objEmail.BodyEncoding = System.Text.Encoding.GetEncoding("ISO-8859-1");

                //Cria objeto com os dados do SMTP
                System.Net.Mail.SmtpClient objSmtp = new System.Net.Mail.SmtpClient();

                //Alocamos o endereço do host para enviar os e-mails  
                objSmtp.Credentials = new System.Net.NetworkCredential(emailRemetente, senha);
                objSmtp.Host = SMTP;
                objSmtp.Port = 587;
                //Caso utilize conta de email do exchange da locaweb deve habilitar o SSL
                //objEmail.EnableSsl = true;

                //Enviamos o e-mail através do método .send()
                try
                {
                    objSmtp.Send(objEmail);
                    // Foi!

                    return RedirectToAction("Index", "Home");
                }
                catch (Exception ex)
                {
                    // Mostra erro
                }
                finally
                {
                    objEmail.Dispose();
                }
            }
            else
            {
                // Instrui o usuário a preencher corretamente o formulário
            }

            return RedirectToAction("Index","Home");
        }
    }
}

BitSolutions/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BitSolutions.Models;
using Digital_Fortress;
using System.Configuration;

namespace BitSolutions.Controllers
{
    public class LoginController : Controller
    {
        UsuarioContext ctxUsuario = new UsuarioContext();
        public ActionResult Index()
        {
            return View();
        }
        
        [HttpPost]
        public ActionResult EfetuaLogin()
        {
            UsuarioETT usuarioTela = new UsuarioETT();
            usuarioTela.Usuario = Request["txtUsuario"];
            usuarioTela.Senha = Request["txtSenha"];

            UsuarioETT usuarioLogin = ctxUsuario.LoginUsuario(usuarioTela.Usuario);

            if (usuarioTela.Senha.Equals(Encrypt_Decrypt.Decrypt(usuarioLogin.Senha, ConfigurationManager.AppSettings["Passphrase"])))
            {
                return RedirectToAction("Index", "Dashboard", new { Id_Usuario = usuarioLogin.Id_Usuario, Id_Site = usuarioLogin.Id_Site });
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }
    }
}

BitSolutions/Views/cadastro_layout.cshtml
<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Melhor Oferta</title>
    <link rel="shortcut icon" type="image/x-icon" href="~/img/logo.png" />

    <link href="~/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/css/bootstrap-theme.min.css" rel="stylesheet">

    <link href="~/css/owl.carousel.css" rel="stylesheet">
    <link href="~/css/owl.theme.default.min.css" rel="stylesheet">

    <link href="~/css/magnific-popup.css" rel="stylesheet">

    <link href="~/css/style.css" rel="stylesheet">


    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
    <div id="menu-item" class="menu-item hide-menu">
        <div class="container">
            <ul>
                <a href="@Url.Action("Index","Home")"><li>home</li></a>
                <a href="@Url.Action("Index","Contato")"><li>contato</li></a>
                <a href="#planos"><li>planos</li></a>
            </ul>
        </div>
    </div>
    <div class="main">
        <div class="main">
            <header>
                <nav class="navbar-reverse navbar-fixed-top">
                    <div class="container-fluid">
                        <!-- Brand and toggle get grouped for better mobile display -->
                        <div class="navbar-header">
                            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                                <span class="sr-only">Toggle navigation</span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </button>

                            <a class="navbar-brand" href="#"><img src="/img/logo.png" style="height:32px;"></a>
                        </div>

                        <!-- Collect the nav links, forms, and other content for toggling -->
                        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                            <ul class="nav navbar-nav">
                                <li><a href="@Url.Action("Index","Home")">Home <span class="sr-only">(current)</span></a></li>
                                <li><a href="@Url.Action("Index","Contato")">Contato</a></li>
                                <li><a href="~/Home/Index/#planos">Planos</a></li>
                            </ul>

                            <ul class="nav navbar-nav navbar-right">
                                <li><a href="@Url.Action("Index","Login")">LOGIN</a></li>
                            </ul>
                        </div><!-- /.navbar-collapse -->
                    </div><!-- /.container-fluid -->

                </nav>
            </header>
            @RenderBody()
            <footer class="footer">
                <div class="container">
                    <div class="row">
                        <div class="col-sm-12">
                        </div>
                    </div>
                </div>
            </footer>
            <script src="~/js/jquery-3.1.1.js"></script>
            <script src="~/js/bootstrap.min.js"></script>
            <script src="~/js/owl.carousel.min.js"></script>
            <script src="https://use.fontawesome.com/55b73bf748.js"></script>
            <script src="~/js/jquery.magnific-popup.js"></script>
            <script src="~/js/script.js"></script>
        </div>
        <footer class="footer">
            <div class="container">
                <div class="row">
                    <div class="col-sm-12">
                        <!-- <p> Handcrafted with <span class="fa fa-heart"></span> by <a href="http://themewagon.com/">ThemeWagon</a></p> -->
                    </div>
                </div>
            </div>
        </footer>
    </div>

    <script src="~/js/jquery-3.1.1.js"></script>
    <script src="~/js/bootstrap.min.js"></script>
    <script src="~/js/owl.carousel.min.js"></script>
    <script src="https://use.fontawesome.com/55b73bf748.js"></script>
    <script src="~/js/jquery.magnific-popup.js"></script>
    <script src="~/js/script.js"></script>
</body>
</html>

BitSolutions/Views/dashboard_layout.cshtml
<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Melhor Oferta</title>
    <link rel="shortcut icon" type="image/x-icon" href="~/img/logo.png" />

    <link href="~/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/css/bootstrap-theme.min.css" rel="stylesheet">

    <link href="~/css/owl.carousel.css" rel="stylesheet">
    <link href="~/css/owl.theme.default.min.css" rel="stylesheet">

    <link href="~/css/magnific-popup.css" rel="stylesheet">

    <link href="~/css/style.css" rel="stylesheet">

    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>

    <script type="text/javascript">
      google.charts.load('current', {'packages':['line']});
      google.charts.setOnLoadCallback(drawChart);

    function drawChart() {

      var data = new google.visualization.DataTable();
      data.addColumn('number', 'Dia');
      data.addColumn('number', 'Minha Loja');
      data.addColumn('number', 'Concorrente 1');
      data.addColumn('number', 'Concorrente 2');

      data.addRows([
        [1,  37.8, 80.8, 41.8],
        [2,  30.9, 69.5, 32.4],
        [3,  25.4,   57, 25.7],
        [4,  11.7, 18.8, 10.5],
        [5,  11.9, 17.6, 10.4],
        [6,   8.8, 13.6,  7.7],
        [7,   7.6, 12.3,  9.6],
        [8,  12.3, 29.2, 10.6],
        [9,  16.9, 42.9, 14.8],
        [10, 12.8, 30.9, 11.6],
        [11,  5.3,  7.9,  4.7],
        [12,  6.6,  8.4,  5.2],
        [13,  4.8,  6.3,  3.6],
        [14,  4.2,  6.2,  3.4]
      ]);

      var options = {
        chart: {
          title: 'Comparação de preço da Saia Longa com concorrentes',
          subtitle: 'Subtítulo'
        },
        width: 450,
        height: 250,
		series: {
		  0: {axis: 'Valor'}
		},
		axes: {
			y: {
				Valor: {label: 'Valor (R$)'}
			}
		}
      };

      var chart = new google.charts.Line(document.getElementById('linechart_material'));
      chart.draw(data, options);

      var chart2 = new google.charts.Line(document.getElementById('linechart_material2'));
      chart2.draw(data, options);
    }
    </script>

    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-96392517-1', 'auto');
      ga('send', 'pageview');

    </script>


    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
    <div id="menu-item" class="menu-item hide-menu">
        <div class="container">
            <ul>
                <a href="index.html"><li>home</li></a>
                <a href="#about"><li>sobre</li></a>
                <a href="#expertise"><li>pacotes</li></a>
            </ul>
        </div>
    </div>
    <div class="main">
        <header>
            <nav class="navbar-reverse navbar-fixed-top">
                <div class="container-fluid">
                    <!-- Brand and toggle get grouped for better mobile display -->
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>

                        <a class="navbar-brand" href="#"><img src="/img/logo.png" style="height:32px;"></a>
                    </div>

                    <!-- Collect the nav links, forms, and other content for toggling -->
                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav">
                            <li><a href="@Url.Action("Index","Home")">Home <span class="sr-only">(current)</span></a></li>
                            <li><a href="@Url.Action("Index","Contato")">Contato</a></li>
                            <li><a href="~/Home/Index/#planos">Planos</a></li>
                        </ul>

                        <ul class="nav navbar-nav navbar-right">
                            <li><a href="@Url.Action("Index","Login")">LOGIN</a></li>
                        </ul>
                    </div><!-- /.navbar-collapse -->
                </div><!-- /.container-fluid -->

            </nav>
        </header>
        @RenderBody()
        <footer class="footer">
            <div class="container">
                <div class="row">
                    <div class="col-sm-12">
                        <!-- <p> Handcrafted with <span class="fa fa-heart"></span> by <a href="http://themewagon.com/">ThemeWagon</a></p> -->
                    </div>
                </div>
            </div>
        </footer>
    </div>

    <script src="~/js/jquery-3.1.1.js"></script>
    <script src="~/js/bootstrap.min.js"></script>
    <script src="~/js/owl.carousel.min.js"></script>
    <script src="https://use.fontawesome.com/55b73bf748.js"></script>
    <script src="~/js/jquery.magnific-popup.js"></script>
    <script src="~/js/script.js"></script>
</body>
</html>

BitSolutions/Views/main_layout.cshtml
<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Melhor Oferta</title>
    <link rel="shortcut icon" type="image/x-icon" href="~/img/logo.png" />

    <link href="~/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/css/bootstrap-theme.min.css" rel="stylesheet">

    <link href="~/css/owl.carousel.css" rel="stylesheet">
    <link href="~/css/owl.theme.default.min.css" rel="stylesheet">

    <link href="~/css/magnific-popup.css" rel="stylesheet">

    <link href="~/css/style.css" rel="stylesheet">

    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-96392517-1', 'auto');
      ga('send', 'pageview');

    </script>

    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
    <div id="menu-item" class="menu-item hide-menu">
        <div class="container">
            <ul>
                <a href="index.html"><li>home</li></a>
                <a href="#about"><li>sobre</li></a>
                <a href="#expertise"><li>pacotes</li></a>
            </ul>
        </div>
    </div>
    <div class="main">
        <header class="bg-img header pagamento">
            <nav class="navbar navbar-default navbar-vira">
                <div class="container">
                    <div class="navigation-bar">
                        <div class="row">
                            <div class="col-xs-6">
                                <div class="logo">
                                    <!-- <a href="index.html"><span class="fa fa-viacoin"></span></a> -->
                                </div>
                            </div>
                            <div class="col-xs-6 text-right">
                                <div class="menu m">
                                    <a href="#"><span class="ion-navicon _ion-android-menu"></span></a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </nav>
            <div class="container">
                <div class="row">
                    <div class="intro-box">
                        <div class="intro">
                            <h1>Pagamento</h1>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        @RenderBody()
        <footer class="footer">
            <div class="container">
                <div class="row">
                    <div class="col-sm-12">
                        <!-- <p> Handcrafted with <span class="fa fa-heart"></span> by <a href="http://themewagon.com/">ThemeWagon</a></p> -->
                    </div>
                </div>
            </div>
        </footer>
    </div>

    <script src="~/js/jquery-3.1.1.js"></script>
    <script src="~/js/bootstrap.min.js"></script>
    <script src="~/js/owl.carousel.min.js"></script>
    <script src="https://use.fontawesome.com/55b73bf748.js"></script>
    <script src="~/js/jquery.magnific-popup.js"></script>
    <script src="~/js/script.js"></script>
</body>
</html>