BitSolutions/Controllers/CriaUsuarioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BitSolutions.Models;
using Digital_Fortress;
using System.Configuration;

namespace BitSolutions.Controllers
{
    public class CriaUsuarioController : Controller
    {
        UsuarioContext ctxUsuario = new UsuarioContext();

        public ActionResult Index(String token)
        {
            token = Encrypt_Decrypt.Encrypt("1", ConfigurationManager.AppSettings["Passphrase"]);

            Int32 Id_Usuario;
            if (Int32.TryParse(Encrypt_Decrypt.Decrypt(token, ConfigurationManager.AppSettings["Passphrase"]), out Id_Usuario))
            {
                return View(Id_Usuario);
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }

        [HttpPost]
        public ActionResult Criar()
        {
            UsuarioETT usuario = new UsuarioETT();
            usuario.Id_Usuario = Convert.ToInt32(Request["hfId_Usuario"]);
            usuario.Nome = Request["txtNome"];
            usuario.Email = Request["txtEmail"];
            usuario.Usuario = Request["txtUsuario"];
            usuario.Senha = Request["txtSenha"];
            usuario.Senha = Encrypt_Decrypt.Encrypt(usuario.Senha, ConfigurationManager.AppSettings["Passphrase"]);
            
            ctxUsuario.AtualizaUsuario(usuario);

            return RedirectToAction("Index", "Login");
        }
    }
}

BitSolutions/Views/CriaUsuario/Index.cshtml
@model Int32
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/cadastro_layout.cshtml";
}

<script type="text/javascript">
    function ValidaSenha() {
        var Senha = document.getElementById("txtSenha").value;
        var ConfSenha = document.getElementById("txtRepeteSenha").value;

        if (Senha != ConfSenha) {
            alert("Senhas não conferem. Por favor, corrija o campo.");
        }
    }
</script>

<section class="purpose section" style="padding-top:350px;">
    <div class="container">
        <h2 class="title">Criar Novo Usuário</h2>
        @using (Html.BeginForm("Criar", "CriaUsuario", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            <input type="hidden" id="hfId_Usuario" name="hfId_Usuario" value="@Model" />
            <div class="row">
                <div class="col-sm-8 col-md-offset-2">
                    <label for="txtNome">Nome Completo</label>
                    <input type="text" id="txtNome" name="txtNome" class="form-control" />
                </div>
                <div class="col-sm-6 col-md-offset-3">
                    <label for="txtEmail">E-mail</label>
                    <input type="text" id="txtEmail" name="txtEmail" class="form-control" />
                </div>
                <div class="col-sm-4 col-md-offset-4">
                    <label for="txtUsuario">Usuário</label>
                    <input type="text" id="txtUsuario" name="txtUsuario" class="form-control" />
                </div>
                <div class="col-sm-4 col-md-offset-4">
                    <label for="txtSenha">Senha</label>
                    <input type="password" id="txtSenha" name="txtSenha" class="form-control" />
                </div>
                <div class="col-sm-4 col-md-offset-4">
                    <label for="txtRepeteSenha">Repita a senha</label>
                    <input type="password" id="txtRepeteSenha" name="txtRepeteSenha" class="form-control" onblur="ValidaSenha()" />
                </div>
                <div class="col-sm-4 col-md-offset-4">
                    <input type="submit" class="vira-btn" value="Cadastrar" />
                </div>
            </div>
        }
    </div>
</section>