BitSolutions/Controllers/DashboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BitSolutions.Models;

namespace BitSolutions.Controllers
{
    public class DashboardController : Controller
    {
        DashboardContext ctxDash = new DashboardContext();
                
        public ActionResult Index(Int32 Id_Usuario, Int32? Id_Site)
        {
            ctxDash = ctxDash.Retorna_Dashboard(Id_Usuario, Id_Site);

            return View(ctxDash);
        }

        [HttpPost]
        public ActionResult AdicionaSite()
        {
            SiteETT site = new SiteETT();
            site.Id_Usuario = Convert.ToInt32(Request["hfId_Usuario"]);
            site.Site = Request["txtNovoSite"];

            site.Id_Site = ctxDash.AdicionaSite(site);

            return RedirectToAction("Index", new { Id_Usuario = site.Id_Usuario, Id_Site = site.Id_Site });
        }

        [HttpPost]
        public ActionResult AdicionaBuscaGoogle()
        {
            RankingGoogleETT ranking = new RankingGoogleETT();
            ranking.Id_Usuario = Convert.ToInt32(Request["hfId_Usuario"]);
            ranking.Id_Site = Convert.ToInt32(Request["hfId_Site"]);
            ranking.Busca = Request["txtNovoPrdGoogle"];

            ctxDash.AdicionaBuscaGoogle(ranking);

            return RedirectToAction("Index", new { Id_Usuario = ranking.Id_Usuario, Id_Site = ranking.Id_Site });
        }

        [HttpPost]
        public ActionResult AdicionaPrecoConcorrencia()
        {
            PrecoConcorrenciaETT preco = new PrecoConcorrenciaETT();
            preco.Id_Usuario = Convert.ToInt32(Request["hfId_Usuario"]);
            preco.Id_Site = Convert.ToInt32(Request["hfId_Site"]);
            preco.Produto = Request["txtNomeProduto"];
            preco.Link_Produto_Usuario = Request["txtLinkSeu"];
            preco.Link_Produto_Concorrencia = Request["txtLinkConc"];

            ctxDash.AdicionaPrecoConcorrencia(preco);

            return RedirectToAction("Index", new { Id_Usuario = preco.Id_Usuario, Id_Site = preco.Id_Site });
        }

        [HttpPost]
        public ActionResult AdicionaComparacaoImagem()
        {
            ImagemConcorrenciaETT imagem = new ImagemConcorrenciaETT();
            imagem.Id_Usuario = Convert.ToInt32(Request["hfId_Usuario"]);
            imagem.Id_Site = Convert.ToInt32(Request["hfId_Site"]);
            imagem.Produto = Request["txtNomeProdutoImagem"];
            imagem.Link_Imagem_Usuario = Request["txtLinkSuaImagem"];
            imagem.Link_Imagem_Concorrencia = Request["txtLinkImagemConc"];

            ctxDash.AdicionaComparacaoImagem(imagem);

            return RedirectToAction("Index", new { Id_Usuario = imagem.Id_Usuario, Id_Site = imagem.Id_Site });
        }
    }
}

BitSolutions/Views/Dashboard/Index.cshtml
@using BitSolutions.Models;
@model DashboardContext

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/dashboard_layout.cshtml";
}

<script>
    function NovoSite() {
        if (document.getElementById('divNovoSite').style.display != '') {
            document.getElementById('divNovoSite').style.display = '';
        }
        else
        {
            document.getElementById('divNovoSite').style.display = 'none';
        }
    }

    function NovoPrdGoogle() {
        if (document.getElementById('divNovoPrdGoogle').style.display != '') {
            document.getElementById('divNovoPrdGoogle').style.display = '';
        }
        else {
            document.getElementById('divNovoPrdGoogle').style.display = 'none';
        }
    }

    function AdicionarPreco() {
        if (document.getElementById('divNovoPrecoConc').style.display != '') {
            document.getElementById('divNovoPrecoConc').style.display = '';
        }
        else {
            document.getElementById('divNovoPrecoConc').style.display = 'none';
        }
    }

    function AdicionaImagem() {
        if (document.getElementById('divNovaImagem').style.display != '') {
            document.getElementById('divNovaImagem').style.display = '';
        }
        else {
            document.getElementById('divNovaImagem').style.display = 'none';
        }
    }
</script>

<div class="container">
    @using (Html.BeginForm("AdicionaSite", "Dashboard", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        <div style="margin-top:350px;">
            <h2>Meu site</h2>
            <div class="row">
                <div class="col-md-4">
                    <select class="form-control" style="padding: 0px 0px 0px 15px;">
                        @foreach (SiteETT site in Model.lstSite)
                        {
                            if (Model.Id_Site != null && site.Id_Site == Model.Id_Site)
                            {
                                <option value="@site.Id_Site" label="@site.Site" selected></option>
                            }
                            else
                            {
                                <option value="@site.Id_Site" label="@site.Site"></option>
                            }
                        }
                    </select>
                </div>
            </div>
            <div class="row" style="padding-bottom:15px;">
                <div class="col-md-4">
                    <button id="btnNovoSite" type="button" class="btn" onclick="NovoSite()">Adicionar Novo Site</button>
                </div>
            </div>
            <div class="row" style="display:none;" id="divNovoSite">
                <div class="col-md-4">
                    <label for="txtNovoSite">Link do site</label>
                    <input type="text" id="txtNovoSite" name="txtNovoSite" class="form-control" placeholder="http://www.seusite.com.br" />
                </div>
                <div class="col-md-1">
                    <input type="submit" id="btnNovoSiteOK" name="btnNovoSiteOK" class="btn" value="OK" />
                </div>
            </div>
        </div>
        <input type="hidden" id="hfId_Usuario" name="hfId_Usuario" value="@Model.Id_Usuario" />
        <input type="hidden" id="hfId_Site" name="hfId_Site" value="@Model.Id_Site" />
    }
    <div class="row" style="margin-top:150px;">
        <div class="col-md-6">
            <div id="linechart_material"></div>
        </div>
        <div class="col-md-6">
            <div id="linechart_material2"></div>
        </div>
    </div>
    <div style="padding-top:80px;">
        <h2>Ranking no Google</h2>
        @using (Html.BeginForm("AdicionaBuscaGoogle", "Dashboard", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            <div class="row" style="padding-bottom:15px;">
                <div class="col-md-2">
                    <button class="btn" onclick="NovoPrdGoogle()" type="button">Adicionar Novo Produto</button>
                </div>
            </div>
            <div class="row" style="display:none;" id="divNovoPrdGoogle">
                <div class="col-md-4">
                    <label for="txtNovoPrdGoogle">Busca no Google</label>
                    <input type="text" id="txtNovoPrdGoogle" name="txtNovoPrdGoogle" class="form-control" placeholder="http://www.linkdoseuproduto.com.br/produto1" />
                </div>
                <div class="col-md-1">
                    <input type="submit" class="btn" value="OK" />
                </div>
            </div>
            <input type="hidden" id="hfId_Usuario" name="hfId_Usuario" value="@Model.Id_Usuario" />
            <input type="hidden" id="hfId_Site" name="hfId_Site" value="@Model.Id_Site" />
        }
        <table class="table">
            <thead style="background-color:#202020 !important;color:#fff;">
                <tr>
                    <th>&nbsp;</th>
                    <th>&nbsp;</th>
                    <th>Busca</th>
                    <th>Pos Atual</th>
                    <th>Pos Anterior</th>
                </tr>
            </thead>
            <tbody style="text-align:left;">
                @foreach (RankingGoogleETT ett in Model.lstRanking)
                {
                    <tr>
                        <td style="border-right:1px solid #ddd;"><a href="#" onclick="ExcluiRanking('@ett.Id_Ranking_Google')"><img src="~/img/cross.gif" /></a></td>
                        <td style="border-right:1px solid #ddd;"><a href="#"><img src="~/img/edit.png" /></a></td>
                        <td style="border-right:1px solid #ddd;">@ett.Busca</td>
                        <td>@ett.Pos_Atual</td>
                        <td>@ett.Pos_Anterior</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>

    <div style="padding-top:80px;">
        <h2>Preço da concorrência</h2>
        @using (Html.BeginForm("AdicionaPrecoConcorrencia", "Dashboard", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            <div class="row" style="padding-bottom:15px;">
                <div class="col-md-2">
                    <button class="btn" type="button" onclick="AdicionarPreco()">Adicionar</button>
                </div>
            </div>
            <div class="row" style="display:none;" id="divNovoPrecoConc">
                <div class="row">
                    <div class="col-md-4">
                        <label for="txtNomeProduto">Nome do Produto</label>
                        <input type="text" id="txtNomeProduto" name="txtNomeProduto" class="form-control" placeholder="Nome" />
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-4">
                        <label for="txtLinkSeu">Link do Seu Produto</label>
                        <input type="text" id="txtLinkSeu" name="txtLinkSeu" class="form-control" placeholder="http://www.linkdoseuproduto.com.br/produto1" />
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-4">
                        <label for="txtLinkConc">Link do Produto da Concorrência</label>
                        <input type="text" id="txtLinkConc" name="txtLinkConc" class="form-control" placeholder="http://www.linkdoseuproduto.com.br/produto1" />
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-1">
                        <input type="submit" class="btn" value="OK" />
                    </div>
                </div>
            </div>
            <input type="hidden" id="hfId_Usuario" name="hfId_Usuario" value="@Model.Id_Usuario" />
            <input type="hidden" id="hfId_Site" name="hfId_Site" value="@Model.Id_Site" />
        }
        <table class="table">
            <thead style="background-color:#202020 !important;color:#fff;">
                <tr>
                    <th>&nbsp;</th>
                    <th>&nbsp;</th>
                    <th>Produto</th>
                    <th>Seu Preço</th>
                    <th>Preço Concorrência</th>
                </tr>
            </thead>
            <tbody style="text-align:left;">
                @foreach (PrecoConcorrenciaETT ett in Model.lstPrecoConcorrencia)
                {
                    <tr>
                        <td style="border-right:1px solid #ddd;"><a href="#"><img src="~/img/cross.gif" /></a></td>
                        <td style="border-right:1px solid #ddd;"><a href="#"><img src="~/img/edit.png" /></a></td>
                        <td style="border-right:1px solid #ddd;">@ett.Produto</td>
                        <td><a href="@ett.Link_Produto_Usuario" target="_blank">R$ @ett.Preco_Usuario</a></td>
                        <td><a href="@ett.Link_Produto_Concorrencia" target="_blank">R$ @ett.Preco_Concorrencia</a></td>
                    </tr>
                }
            </tbody>
        </table>
    </div>

    <div style="padding-top:80px;">
        <h2>Comparação de imagens</h2>
        @using (Html.BeginForm("AdicionaComparacaoImagem", "Dashboard", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
        <div class="row" style="padding-bottom:15px;">
            <div class="col-md-2">
                <button type="button" onclick="AdicionaImagem()" class="btn">Adicionar Nova Imagem</button>
            </div>
        </div>
            <div class="row" style="display:none;" id="divNovaImagem">
                <div class="row">
                    <div class="col-md-4">
                        <label for="txtNomeProdutoImagem">Nome do Produto</label>
                        <input type="text" id="txtNomeProdutoImagem" name="txtNomeProdutoImagem" class="form-control" placeholder="Nome" />
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-4">
                        <label for="txtLinkSuaImagem">Link da Imagem do seu Produto</label>
                        <input type="text" id="txtLinkSuaImagem" name="txtLinkSuaImagem" class="form-control" placeholder="http://www.linkdoseuproduto.com.br/imagem1" />
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-4">
                        <label for="txtLinkImagemConc">Link da Imagem do Produto da Concorrência</label>
                        <input type="text" id="txtLinkImagemConc" name="txtLinkImagemConc" class="form-control" placeholder="http://www.linkdoseuproduto.com.br/imagem2" />
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-1">
                        <input type="submit" class="btn" value="OK" />
                    </div>
                </div>
            </div>
            <input type="hidden" id="hfId_Usuario" name="hfId_Usuario" value="@Model.Id_Usuario" />
            <input type="hidden" id="hfId_Site" name="hfId_Site" value="@Model.Id_Site" />
        }
        <table class="table">
            <thead style="background-color:#202020 !important;color:#fff;">
                <tr>
                    <th>&nbsp;</th>
                    <th>&nbsp;</th>
                    <th>Produto</th>
                    <th style="text-align:center;">Sua imagem</th>
                    <th style="text-align:center;">Imagem da concorrência</th>
                </tr>
            </thead>
            <tbody style="text-align:left;">
                @foreach (ImagemConcorrenciaETT ett in Model.lstImagemConcorrencia)
                {
                    <tr>
                        <td style="border-right:1px solid #ddd;"><a href="#"><img src="~/img/cross.gif" /></a></td>
                        <td style="border-right:1px solid #ddd;"><a href="#"><img src="~/img/edit.png" /></a></td>
                        <td style="border-right:1px solid #ddd;">@ett.Produto</td>
                        <td style="text-align:center;"><a href="@ett.Link_Imagem_Usuario" target="_blank"><img src="@ett.Link_Imagem_Usuario" style="max-width:80px;max-height:80px" /></a></td>
                        <td style="text-align:center;"><a href="@ett.Link_Imagem_Concorrencia" target="_blank"><img src="@ett.Link_Imagem_Concorrencia" style="max-width:80px;max-height:80px" /></a></td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
    </div>